# Generated by Django 3.2.14 on 2022-11-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0017_auto_20220711_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='is_vip',
        ),
        migrations.AlterField(
            model_name='thread',
            name='close_reason',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'duplicate question'), (2, 'question is off-topic or not relevant'), (3, 'too subjective and argumentative'), (4, 'not a real question'), (5, 'the question is answered, right answer was accepted'), (6, 'question is not relevant or outdated'), (7, 'question contains offensive or malicious remarks'), (8, 'spam or advertising'), (9, 'too localized'), (10, 'question is considered as answered'), (11, 'closed as inactive')], null=True),
        ),
    ]
