# Generated by Django 3.2.14 on 2022-12-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0019_auto_20221119_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='can_upload_files',
            field=models.BooleanField(default=False),
        ),
    ]
