# Generated by Django 3.2.14 on 2022-11-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0018_auto_20221119_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='moderate_answers_to_enquirers',
        ),
    ]
