# Generated by Django 3.2.14 on 2023-07-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0022_auto_20230408_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='close_reason_text',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
