# Generated by Django 4.2.4 on 2023-10-01 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('askbot', '0024_init_close_reason_text_20230724_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_is_confidential',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postrevision',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
